# Generated by Django 3.2.6 on 2021-08-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
